#!/bin/bash
# iobroker diagnostics
# written to help getting information about the environment the ioBroker installation is running in
clear;

# VARIABLES
XORGTEST=0;
DOCKER=/opt/scripts/.docker_config/.thisisdocker;
APT=0

#if [ $EUID -eq 0 ] | [ ! -f "$DOCKER" ]; then
#  echo -e "Dieses Skript darf nicht von root ausgeführt werden! \nBitte als Standarduser ausführen!" 1>&2
#  exit 1
#fi

echo "";
echo -e "\033[34;107m*** ioBroker Diagnose ***\033[0m";
echo "";
echo "Bitte das Fenster des Terminalsprogramms (puTTY) breit ziehen oder auf Vollbild setzen.";
echo "Die nachfolgenden Diagnosen können einen Hinweis auf mögliche Fehler im Setup liefern";
echo "https://forum.iobroker.net";
echo "Die Zusammenfassund am Ende bitte vollständig im Forum posten, inkl der jeweils drei Steuerzeichen \`\`\`.";
echo "Das hilft den Helfern enorm dabei zu erkennen wo ein Problem evtl. zu suchen ist"
echo "";
        read -p "Weiter mit Enter";
echo "";
echo -e "\033[33m=========== DIAGNOSE ==========\033[0m";
echo "";
echo "\`\`\`";
echo -e "\033[34;107m*** BASISSYSTEM ***\033[0m";
echo -n "CPU-Architektur: ";
        uname -m;
if [ -f "$DOCKER" ]; then
    echo "Docker: Ja"
else
    echo "Docker: Nein"
fi;
# Alternativer DockerCheck - Nicht getestet:
#
# if [ -f /.dockerenv ]; then
#    echo "I'm inside matrix ;(";
# else
#    echo "I'm living in real world!";
# fi
echo -e "LXC: `systemd-detect-virt`"
        lsb_release -idrc;
echo "";
        cat /etc/os-release;
echo "";
echo "Systemuptime und Load:";
        uptime;
echo "CPU threads: $(grep -c processor /proc/cpuinfo)"
echo "";
echo -e "\033[34;107m*** Zeit und Zeitzonen ***\033[0m";
        date -u;
        date;
        date +"%Z %z";
        cat /etc/timezone;
echo "";
echo -e "\033[34;107m*** User und Gruppen ***\033[0m";
        whoami;
        pwd;
        groups;
echo "";
echo -e "\033[34;107m*** X-Server-Setup ***\033[0m";

XORGTEST=`ps aux | grep -c 'Xorg'`
if (("$XORGTEST" > 1)); then
    echo "X-Server: Ja"
else
    echo "X-Server: Nein"
fi
echo -e "Desktop: $DESKTOP_SESSION";
echo -e "Konsole: $XDG_SESSION_TYPE";
echo "";
echo -e "\033[34;107m*** ARBEITSSPEICHER ***\033[0m";
        free -th --mega;
echo "";
        vmstat -S M -s | head -n 10;
echo "";
echo -e "\033[34;107m*** DATEISYSTEM ***\033[0m";
        df -PTh;
echo "";
echo -e "\033[32mDaten in neuralgischen Verzeichnissen:\033[0m";
echo "";
echo -e  "\033[32m/var:\033[0m";
        sudo du -h /var/ | sort -rh | head -5;
echo "";
echo -e "\033[32m/opt/iobroker/backups:\033[0m";
        du -h /opt/iobroker/backups/ | sort -rh | head -5;
echo "";
echo -e "\033[32m/opt/iobroker/iobroker-data:\033[0m";
        du -h /opt/iobroker/iobroker-data/ | sort -rh | head -5;
echo "";
echo -e "\033[32mDie 5 größten Dateien in iobroker-data:\033[0m";
        ls -sh /opt/iobroker/iobroker-data/ | sort -rh | head -5;
echo "";
echo -e "\033[34;107m*** Nodejs-Installation ***\033[0m";
sudo ln -s /usr/bin/node /usr/bin/nodejs &> /dev/null;
echo -e "`type -P nodejs` \t`nodejs -v`";
echo -e "`type -P node` \t\t`node -v`";
echo -e "`type -P npm` \t\t`npm -v`";
echo "";
        apt-cache policy nodejs;
echo  "";
echo -e "\033[34;107m*** ioBroker-Installation ***\033[0m";
echo "";
echo -e "\033[32mVersionsnummern der Kern-Adapter\033[0m"
echo -e "js-controller: \t`iob -v`";
echo -e "Admin-Adapter: \t`iob version admin`";
echo "";
echo -e "\033[32mioBroker-Repos und Updates\033[0m";
        iob repo list;
echo "";
        iob update -u;
echo "";
echo -e "\033[32mObjekte und Zustände\033[0m";
echo "werden ermittelt - Dies kann einen Moment dauern.";
echo -e "Objekte: \t`iob list objects 2>/dev/null | wc -l`";
echo -e "Zustände: \t`iob list states 2>/dev/null | wc -l`";
echo "";
echo -e "\033[34;107m*** Repositories und OS-Updates ***\033[0m";
        sudo apt-get update 1>/dev/null && sudo apt-get update
        APT=`apt-get upgrade -s |grep -P '^\d+ upgraded'|cut -d" " -f1`
echo -e "Ausstehende Updates: `echo $APT`";
echo "";

echo -e "\033[34;107m*** Lauschende Ports ***\033[0m";
        sudo netstat -tulpen #| sed -n '1,2p;/LISTEN/p';
# Alternativ - ss ist nicht ueberall installiert
# sudo ss -tulwp | grep LISTEN;
echo "";
echo "\`\`\`";
echo "";

echo -e "\033[33m=========== Voll-Diagnose hier kopieren ===========\033[0m";
echo "";
echo "iob diag wurde beendet.";
echo "";
echo "";
        read -p "Zur Zusammenfassung drücke die Enter-Taste";
echo "";
        clear;
echo "========= ZUSAMMENFASSUNG =========";
echo "";
echo "Is noch nich' fertig. Erstmal Mittagspause machen!";
echo "";
exit;
